# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chapter3_List' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Chapter3_List

end

target 'Data Structures' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Data Structures

end

target 'Data Structures Tests' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Data Structures Tests

end
